/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conexion;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanKuzo
 */
public class VistaPrevia extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrevia
     */
    public VistaPrevia() {
        initComponents();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        Seleccionar = new javax.swing.JMenuItem();
        regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Folio = new javax.swing.JLabel();
        clavePro = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPDF = new javax.swing.JTable();
        salir = new javax.swing.JButton();

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Seleccionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista Previa PDF");

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        jLabel1.setText("Folio");

        jLabel2.setText("Clave_Pro");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Cantidad");

        jLabel6.setText("Descripcion");

        jLabel7.setText("Precio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Folio))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clavePro))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Nombre))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Direccion))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Cantidad))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Descripcion)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imprimir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(Precio)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Folio)
                    .addComponent(clavePro)
                    .addComponent(Nombre)
                    .addComponent(Direccion)
                    .addComponent(Cantidad)
                    .addComponent(Descripcion)
                    .addComponent(Precio))
                .addGap(66, 66, 66)
                .addComponent(imprimir)
                .addContainerGap())
        );

        tbPDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPDF.setComponentPopupMenu(jPopupMenu2);
        jScrollPane1.setViewportView(tbPDF);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(regresar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Productos t = new Productos();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);

    }//GEN-LAST:event_salirActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        mostrarPrevia();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        Document document = new Document();
        DateTimeFormatter dia = DateTimeFormatter.ofPattern("yyyy/MMMM/dd");
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(document, new FileOutputStream(ruta + "/Documents/Folios/" + Folio.getText() + "Folio.pdf"));

            Image image = Image.getInstance("src/imagenes/oxxo.png");
            image.scaleToFit(500, 2000);
            image.setAlignment(Chunk.ALIGN_CENTER);

            Image sello = Image.getInstance("src/imagenes/confirmado.jpg");
            sello.scaleToFit(100, 1000);
            sello.setAlignment(Paragraph.ALIGN_RIGHT);

            Paragraph titulo = new Paragraph("Factura del producto\n\n", FontFactory.getFont("Arial", 16, Font.BOLDITALIC, BaseColor.ORANGE));
            titulo.setAlignment(Paragraph.ALIGN_CENTER);
            Paragraph parrafo = new Paragraph("", FontFactory.getFont("Arial", 16, Font.BOLDITALIC, BaseColor.ORANGE));
            Paragraph datos = new Paragraph("", FontFactory.getFont("Arial", 16, Font.BOLDITALIC, BaseColor.RED));

            Paragraph Espacios = new Paragraph();
            Espacios.add("\n\n\n\n");
            parrafo.setAlignment(Paragraph.ALIGN_LEFT);
            datos.setAlignment(Paragraph.ALIGN_LEFT);
            parrafo.add("Factura Electronica\n");
            datos.add("Folio:" + Folio.getText() + "\n");
            datos.add("No:" + Folio.getText() + "\n");
            datos.add("Fecha: " + dia.format(LocalDateTime.now()) + "\n");
            datos.add("Documento Para Pasar el Semestre\n\n");
            datos.setFont(FontFactory.getFont("Arial", 16, Font.BOLDITALIC, BaseColor.BLACK));

            Paragraph tituloCompra = new Paragraph("Detalles de la compra del cliente\n\n", FontFactory.getFont("Arial", 16, Font.BOLDITALIC, BaseColor.ORANGE));
            tituloCompra.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph detalleCompra = new Paragraph("", FontFactory.getFont("Arial", 12, Font.BOLD, BaseColor.RED));
            detalleCompra.setAlignment(Paragraph.ALIGN_RIGHT);
            detalleCompra.add("Prodcuto: " + Descripcion.getText() + "\n");
            detalleCompra.add("Clave del producto: " + clavePro.getText() + "\n");
            detalleCompra.add("Cantidad: " + Cantidad.getText() + "\n");
            detalleCompra.add("Precio: " + Precio.getText() + "\n");
            detalleCompra.add("IVA ya incluida\n");
            detalleCompra.add("Total a pagar: " + (String.valueOf((Integer.parseInt(Cantidad.getText())) * (Integer.parseInt(Precio.getText())))) + ".00 Pesos\n");
            detalleCompra.add("Gracias por su compra\n");
            document.open();

            document.add(image);
            document.add(parrafo);
            document.add(datos);
            document.add(titulo);

            PdfPTable table = new PdfPTable(7);
            table.addCell(new Paragraph("Folio", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Clave_Pro", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Nombre del Cliente", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Direccion", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Cantidad", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Descripcion", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph("Precio", FontFactory.getFont("Arial", 12, Font.BOLDITALIC, BaseColor.ORANGE)));
            table.addCell(new Paragraph(Folio.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(clavePro.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(Nombre.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(Direccion.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(Cantidad.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(Descripcion.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));
            table.addCell(new Paragraph(Precio.getText(), FontFactory.getFont("Arial", 12, BaseColor.RED)));

            document.add(table);
            document.add(Espacios);
            document.add(tituloCompra);
            document.add(detalleCompra);
            document.add(sello);
            document.close();
            JOptionPane.showMessageDialog(null, "Factura generada correctamente");
        } catch (Exception e) {
            System.out.println("error " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error Folio generado correctamente");
        }
    }//GEN-LAST:event_imprimirActionPerformed
    void mostrarPrevia() {
        int filas = tbPDF.getSelectedRow();
        if (filas > 0) {
            Folio.setText(tbPDF.getValueAt(filas, 0).toString());
            clavePro.setText(tbPDF.getValueAt(filas, 1).toString());
            Nombre.setText(tbPDF.getValueAt(filas, 2).toString());
            Direccion.setText(tbPDF.getValueAt(filas, 3).toString());
            Cantidad.setText(tbPDF.getValueAt(filas, 4).toString());
            Descripcion.setText(tbPDF.getValueAt(filas, 5).toString());
            Precio.setText(tbPDF.getValueAt(filas, 6).toString());

        }
    }

    void mostrarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Folio");
        modelo.addColumn("Clave_Pro");
        modelo.addColumn("Nombre del Cliente");
        modelo.addColumn("Direccion");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        tbPDF.setModel(modelo);
        String sql = "";
        if (sql.equals("")) {
            sql = "select fa.FOLIO,pro.CLAVE_P, c.NOMBRE_C,c.DIRECCION_C,"
                    + " df.CANTIDAD, pro.DESCRIPCION,pro.PRECIO"
                    + " from clientes c inner join factura fa "
                    + "on fa.CLAVE_C=c.CLAVE_C  "
                    + "inner join detallefactura df on fa.FOLIO=df.FOLIO "
                    + "inner join productos pro on pro.CLAVE_P=df.CLAVE_P;";
        }
        String[] datos = new String[7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);

                modelo.addRow(datos);
            }
            tbPDF.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println("error " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrevia().setVisible(true);
            }
        });
    }
    NuevaConexion cc = new NuevaConexion();
    Connection cn = cc.conexion();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Folio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JMenuItem Seleccionar;
    private javax.swing.JLabel clavePro;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    private javax.swing.JButton salir;
    private javax.swing.JTable tbPDF;
    // End of variables declaration//GEN-END:variables
}
